# Generated by Django 4.2.7 on 2023-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_death_year_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='books.character', verbose_name='Персонажи'),
        ),
    ]
