# Generated by Django 4.2.7 on 2024-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_url_character_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
